### PR TITLE
Split Closure Templates translater to separate project

### PR DESCRIPTION
**Pull request by bregenspan**
### What does this PR do? How does it affect users?

This removes code and tests that have been moved to https://github.com/gawkermedia/fast-closure-translater. The goal of splitting the project was to decouple, allowing the translater to be used independently of Webpack (for example, in <a href="http://karma-runner.github.io/0.13/config/preprocessors.html">a Karma preprocessor</a>, our immediate internal use-cae for this).

### How should this be tested (feature switches, URLs, special user permissions)?

Verify that the plugin continues to function as normal. As the plugin itself is mostly glue code, the priority in test coverage was on the translater itself -- those tests remain, although they have been moved out of this repository.

### Related Trello card, wiki page or blog posts

https://trello.com/c/5StMSJqL/132-eliminate-dependency-of-tests-on-locale-specific-templates

### CODE REVIEW

**Comment by bregenspan** [comment]
@yaanno since I've already discussed a related issue with you and it relates to Performance team, could I run this one by you?

Also @gazs since you're taking over Performance, I think it could be good to get your eyes on this, just so you're aware of latest Webpack setup.

**Comment by bregenspan** [comment]
(NOTE: Travis CI build fails reported here are due to removal of the tests as they related to the subproject that has now been moved out. Even though this plugin is glue code and important functionality lives there, I'll add some separate test that at least makes sure it initializes properly)

**Comment by bregenspan** [comment]
(The moved test suite on Travis: https://travis-ci.org/gawkermedia/fast-closure-translater)

**Comment by yaanno** [comment]
lgtm!

**Comment by bregenspan** [comment]
Just added in a super-dumb test skeleton, just to make sure that dependencies are configured properly remain that way.

**Pull request merged**
